### ISSUE TITLE
Implement 1st set of routes

### ISSUE THREAD

**Issue by okas** [okas/reboot-techproject2-lender#13]
### TODO:

- [ ] ~~Convert current auth/authz related model to the on specified in schema:~~
  - [ ] ~~AppUser:  lender/admin-like~~
  - [ ] ~~Borrower: borrower/restricted-like~~
- [x] ~~Refactor common properties to SubSchema/embedded document: password and claims into this.~~
- [x] Incorporated both user type properties into one, as it needs more work to separate them.
- [x] Contract:
- [x] Contract's embedded document Payment
- [x] Account (of lender)
